name: Github Pages Deploy
on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: git clone https://github.com/myselfmohith/myselfmohith.github.io.git .
      - uses: actions/configure-pages@v5
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dst'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4