name: Github Pages Deploy
on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Clone
        run: git clone https://github.com/myselfmohith/myselfmohith.github.io.git; cd myselfmohith.github.io
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install NPM
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dst'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4